In [2]:
# Import necessary libraries
import os
from PIL import Image
import numpy as np
import tensorflow as tf
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim
from torch.nn import Module, Sequential, Conv2d, ConvTranspose2d, LeakyReLU, BatchNorm2d, ReLU, Tanh, Sigmoid, BCELoss 
import matplotlib.pyplot as plt

In [3]:
# Path to the dataset
dataset_path = 'formatted'

# Load the dataset into memory
dataset = []
for img in os.listdir(dataset_path):
    image = Image.open(os.path.join(dataset_path,img))
    dataset.append(np.asarray(image))
    
dataset=np.asarray(dataset)
#print(dataset[:5])

In [4]:
# Normalize the dataset
dataset = (dataset.astype('float32') / 255.0 - 0.5) * 2.0

In [5]:
print(dataset[:5])
# values in range of [-0.5, 0.5] 

[[[[ 0.17647064  0.09803927  0.05882359]
   [ 0.21568632  0.13725495  0.09803927]
   [ 0.3176471   0.24705887  0.1686275 ]
   ...
   [ 0.41960788  0.05882359 -0.20784312]
   [ 0.26274514 -0.09803921 -0.36470586]
   [ 0.15294123 -0.20784312 -0.47450978]]

  [[ 0.20000005  0.12156868  0.06666672]
   [ 0.2313726   0.15294123  0.09803927]
   [ 0.34901965  0.27843142  0.18431377]
   ...
   [ 0.5058824   0.12156868 -0.12156862]
   [ 0.3176471  -0.04313725 -0.3098039 ]
   [ 0.082353   -0.27843136 -0.54509807]]

  [[ 0.21568632  0.14509809  0.06666672]
   [ 0.20784318  0.13725495  0.05882359]
   [ 0.3411765   0.27058828  0.17647064]
   ...
   [ 0.7411765   0.37254906  0.14509809]
   [ 0.41960788  0.07450986 -0.19999999]
   [-0.01176471 -0.35686272 -0.6313726 ]]

  ...

  [[ 0.11372554 -0.1607843  -0.30196077]
   [ 0.07450986 -0.19999999 -0.34117645]
   [ 0.09803927 -0.16862744 -0.2862745 ]
   ...
   [-0.09803921 -0.54509807 -0.654902  ]
   [-0.23921567 -0.5686275  -0.7019608 ]
   [-0.19999999 

In [6]:
# Reshape the dataset
dataset = np.reshape(dataset, (dataset.shape[0], 1280, 1024, 3))

In [7]:
dataset.shape
# 1000 images with a size of 1280x1024 pixels and 3 color channels (RGB)

(1000, 1280, 1024, 3)

In [8]:
# Shuffle the dataset
np.random.shuffle(dataset) # prevent overfitting

In [13]:
dataset[:5]
# checkpoint: normalized, reshaped and randomly shuffled dataset

array([[[[ 0.41960788,  0.10588241, -0.372549  ],
         [ 0.41960788,  0.10588241, -0.372549  ],
         [ 0.41960788,  0.14509809, -0.34117645],
         ...,
         [ 0.69411767,  0.67058825,  0.18431377],
         [ 0.8117647 ,  0.79607844,  0.28627455],
         [ 0.827451  ,  0.8117647 ,  0.30196083]],

        [[ 0.78039217,  0.7647059 ,  0.23921573],
         [ 0.77254903,  0.75686276,  0.2313726 ],
         [ 0.75686276,  0.7254902 ,  0.1686275 ],
         ...,
         [ 0.58431375,  0.56078434,  0.10588241],
         [ 0.5294118 ,  0.4666667 ,  0.01176476],
         [ 0.5686275 ,  0.5058824 ,  0.05098045]],

        [[ 0.67058825,  0.5372549 ,  0.05098045],
         [ 0.6392157 ,  0.5058824 ,  0.0196079 ],
         [ 0.6       ,  0.48235297, -0.08235294],
         ...,
         [ 0.5686275 ,  0.27058828, -0.20784312],
         [ 0.56078434,  0.26274514, -0.19999999],
         [ 0.6313726 ,  0.33333337, -0.12941176]],

        ...,

        [[ 0.60784316,  0.28627455, -0

In [14]:
X_train = dataset
# store X_train locally as .npy file for future use
# np.savez_compressed('images_1280_1024.npz', X_train) # line comment to not execute again by mistake

In [15]:
# X_train=np.load('images_1280_1024.npz')
# X_train.values